name:                task-machine
version:             0.1.0.0
github:              "Garmelon/task-machine"
license:             BSD3
author:              "Joscha Mennicken"
maintainer:          "joscha@migejolise.de"
copyright:           "Joscha Mennicken"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Garmelon/task-machine#readme>

dependencies:
- base >= 4.7 && < 5
  #- ConfigFile
  #- aeson
  #- async
- brick
  #- bytestring
- containers
- megaparsec
- optparse-applicative
  #- sqlite-simple
  #- stm
  #- text
  #- text-zipper
- time
  #- transformers
  #- unix
  #- unordered-containers
- vector
- vty
# tests
- hspec
- QuickCheck

library:
  source-dirs: src

executables:
  task-machine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - task-machine

tests:
  task-machine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - task-machine
